name: deploy
on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app-deploy.yml'
  workflow_dispatch:
jobs:
  app-deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN_NAME: 'borrowbot.kibalabs.com'
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app-prod:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/
          target: build
          load: true
          cache-from: type=gha,scope=app-prod
          cache-to: type=gha,mode=max,scope=app-prod
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Extract built files
        run: |
          docker create --name extract ${{ env.DOCKER_IMAGE }}
          docker cp extract:/app/dist ./app/dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SITE_DEPLOYER_AWS_REGION }}
      - name: Sync to S3
        run: |
          aws s3 sync \
            ./app/dist \
            s3://${{ secrets.SITE_DEPLOYMENT_S3_BUCKET_NAME }}/${{ env.DOMAIN_NAME }}/
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.SITE_DEPLOYMENT_CLOUDFRONT_ID }} \
            --paths "/${{ env.DOMAIN_NAME }}/*"
